version: '2'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # command: --interval 1800 factorio --cleanup
    restart: always
    environment:
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      TZ: Europe/London
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
  factorio:
    container_name: factorio
    image: factoriotools/factorio:stable
    restart: always
    build:
      context: .
      args:
        # Check buildinfo.json for supported versions and SHAs
        # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
        - VERSION=2.0.23
        - SHA256=e819fc9ad6df061bf9d4bffc91988dd18d0e3982c8b1c22c0525d78bda3ef216
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /opt/factorio:/factorio
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - UPDATE_MODS_ON_START=true
#      - USERNAME=FactorioUsername
#      - TOKEN=FactorioToken
#      - PORT=34198
#      - PRESET=deathworld
#      - ADDR=::1
